### ISSUE TITLE
Add RSS or Atom feed to blog

### ISSUE THREAD

**Issue by alexott** [john2x/john2x.github.com#1]
I've found your blog post about Clojure (http://john2x.com/blog/clojure-destructuring/) and want to add your blog to Planet Clojure. To do this I need RSS or Atom feed, and the best - if you can provide per-tag/label feed. If this could cause troubles, then I can filter only Clojure-related posts from full feed (using the Yahoo Pipes)

Thanks

**Comment by john2x** [comment]
I've added an rss feed at http://john2x.com/rss.xml. No per-tag feed yet though. I'll keep this open so I won't forget to add them later on.

Thanks

**Comment by alexott** [comment]
Thanks - I've added your feed to Planet Clojure (filtered through Yahoo Pipes)
